version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build frontend
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: gabrielcheong/the-mini-mart
    steps:
      - checkout
      - setup_remote_docker      
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan: 
        docker-image-name: $IMAGE_NAME
  # publish:
    # - docker/check:
    #         docker-username: DOCKERHUB_LOGIN  # already setup on project's github to push to gab's docker
    #         docker-password: DOCKERHUB_PASSWORD  # already setup on project's github to push to gab's docker
  # deploy:

# Develop Workflow: build-test-scan
# Release Workflow: build-test-scan-publish-deploy
workflows:
  simple_workflow:
    jobs:
      - build:
        filters:
          branches:
            only:
              - /^develop.*/
              - /^release\/.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - /^develop.*/
                - /^release\/.*/
      - scan:
          requires:
            - build
          filters:
            branches:
              only:
                - /^develop.*/
                - /^release\/.*/ 
      # - publish
      # - deploy
