version: 2.1

orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build frontend
          command: npm run build

  # test:
  # scan:
  # publish:
  # deploy:

# Develop Workflow: build-test-scan
# Release Workflow: build-test-scan-publish-deploy
workflows:
  simple_workflow:
    jobs:
      - build
      # - test
      # - scan
      # - publish
      # - deploy
